### ISSUE TITLE
Suppress broken pipe message

### ISSUE THREAD

**Issue by fowles** [janestreet/patdiff#1] opened 2014-10-06 15:38 UTC
When I produce a large diff and pipe it to less, sometimes I will quit less before patdiff has processed the whole file.  This will produce the error:

  (Sys_error "Broken pipe")

Called from file "pervasives.ml", line 449, characters 30-33
Called from file "pervasives.ml", line 454, characters 2-15
Called from file "lib/deprecated_command.ml", line 819, characters 14-20
Called from file "lib/command.ml", line 1678, characters 6-68
Called from file "lib/exn.ml", line 80, characters 6-10
(Sys_error "Broken pipe")
Fatal error: exception Sys_error("Broken pipe")
Called from file "pervasives.ml", line 449, characters 30-33
Called from file "pervasives.ml", line 454, characters 2-15
Called from file "bin/patdiff.ml", line 11, characters 55-61
External program "patdiff" failed with exit code 2

I would like to suppress this error (normal diff does not produce an error when the output pipe is closed early).

**Comment by bcc32** [comment] 2020-06-05 16:40
Thank you for reporting this bug, and sorry it did not get a response for so long.

I'm unable to reproduce this error under normal conditions.  I was able to trigger this error message when running a certain kind of test setup, but that appears to be because [ignored signals are inherited by child processes](https://github.com/golang/go/issues/20479#issuecomment-303791827).  Basically, if the process which eventually spawns patdiff sets its SIGPIPE behavior to SIG_IGN (ignore), then that will be inherited by patdiff.  If SIGPIPE is ignored in an OCaml program, the `write` syscall instead returns EPIPE, which manifests as the error message you showed above.

Since I am no longer able to reproduce this except in that specific case, and since this issue is very old, I'm going to close it.  If this comes up again, please feel free to reopen or open a new issue with more details about the environment where you observed the error.

**Closed by bcc32** 2020-06-05 16:40 UTC
Labels: forwarded-to-js-devs

**Comment by fowles** [comment] 2020-06-05 16:45
I just wanted to say thank you for taking the time to go through old bug reports.  It is under appreciated as a task that genuinely does help others.
